### ISSUE TITLE
ImportError: DLL load failed while importing pybind: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by AzlanCoding** [AhmedAskar12/Movmi#1]
Hello, I recently installed the Movmi V1.4.0 (CPU) version but it doesn't seem to work. I created and account (but left affiliation blank) and then clicked register. However, after that, It brought me to a loading page and the loading sign got stuck. Then this pop-up appeared:
![image](https://user-images.githubusercontent.com/101229146/179177896-15157698-21fb-40ac-8246-198ebd3f21f4.png)
```
Traceback (most recent call last):
  File "Movmi.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "open3d\__init__.py", line 75, in <module>
ImportError: DLL load failed while importing pybind: A dynamic link library (DLL) initialization routine failed.
```
I happen to have python 3.10 installed and I'm not sure if it is affecting Movmi. I downloaded Movmi on my phone overnight and transfered it to my computer via USB two days later in the afternoon.

**Comment by AzlanCoding** [comment]
Also your site certificate expired 
![image](https://user-images.githubusercontent.com/101229146/179179174-9c69c7db-3328-472b-a539-a290617d758a.png)
